# Site settings
title: N.B.ryy
description: Record something for ryy
# baseurl: "" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: N.B.ryy
user_description: This person is very cold, she did not introduce anything!
user_title: A fan of ayunga 
email: 21831111@zju.edu.cn
# twitter_username: lorem_ipsum
github_username:  ningboryy
# gplus_username:  lorem_ipsum

# Google-analytics
#google-analytics:
 # id: ""

exclude: ['package.json', 'src' , 'node_modules']